services:
  fswd-mobile-banking-db:
    image: postgres:16.9-bullseye
    container_name: fswd-mobile-banking-db
    ports:
      - "9999:5432"
    environment:
      POSTGRES_PASSWORD: benz
      POSTGRES_USER: benz
      POSTGRES_DB: fswd_mobile_banking_db
    volumes:
      - fswd-mobile-banking-vol:/var/lib/postgresql/data

volumes:
  fswd-mobile-banking-vol: